### ISSUE TITLE
Homework Link

### ISSUE THREAD

**Issue by StephenGothe** [rstropek-teaching/turmrechnen-quiz-4bhif-StephenGothe#1]
Editor URL: https://stackblitz.com/edit/silly-turmrechnen
APP URL: https://silly-turmrechnen.stackblitz.io

By Stefan Greß

**Comment by rstropek** [comment]
Hi @StephenGothe 

Thank you for the link. It works as expected, your extra point is secured.

However, I recommend that you refactor your solution. Building the HTML in TypeScript and using a binding to innerHTML is not optimal. Prefer an *ngFor loop instead.

BTW - your approach is similar to the one of your colleague *micky8186*. Did you create the solution together or did you create the approach independent of each other? Both things are ok for me, I am just curious because I did not expect solutions with HTML-building in TypeScript.

Greetings,
Rainer Stropek.

**Comment by StephenGothe** [comment]
We created the homework independent of each other, but he gave me some hints.
